version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: bookshop-api-nginx
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - bookshop-api

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: bookshop-api-php
    volumes:
      - ./:/var/www/html/
    networks:
      - bookshop-api

networks:
  bookshop-api: